// Stripe product and price IDs
// Generated by scripts/generate-stripe-products.ts
// IDs are loaded from environment variables for security

export const stripeIds = {
    products: {
        gmbMax: process.env.STRIPE_PRODUCT_GMB_MAX!,
        googleOrganic: process.env.STRIPE_PRODUCT_GOOGLE_ORGANIC!,
    },
    prices: {
        gmbMaxMonthly: process.env.STRIPE_PRICE_GMB_MAX_MONTHLY!,
        googleOrganicMonthly: process.env.STRIPE_PRICE_GOOGLE_ORGANIC_MONTHLY!,
    },
    coupons: {
        SEO70: process.env.STRIPE_COUPON_SEO70!,
    },
} as const;


// Helper function to get price ID by service ID
export function getPriceIdByServiceId(serviceId: number | string): string | null {
    console.log('getPriceIdByServiceId called with:', serviceId, 'type:', typeof serviceId);
    console.log('stripeIds.prices:', stripeIds.prices);

    const id = typeof serviceId === 'string' ? parseInt(serviceId, 10) : serviceId;
    console.log('Parsed ID:', id);

    switch (id) {
        case 1:
            return stripeIds.prices.gmbMaxMonthly;
        case 2:
            return stripeIds.prices.googleOrganicMonthly;
        default:
            return null;
    }
}

// Helper function to get product ID by service ID
export function getProductIdByServiceId(serviceId: number): string | null {
    switch (serviceId) {
        case 1:
            return stripeIds.products.gmbMax;
        case 2:
            return stripeIds.products.googleOrganic;
        default:
            return null;
    }
}
