// Stripe product and price IDs
// Generated by scripts/required-generate-stripe.ts
// IDs are loaded from environment variables for security

export const stripeIds = {
    products: {
        gmbmax: process.env.STRIPE_PRODUCT_GMB_MAX!,
        googleorganic: process.env.STRIPE_PRODUCT_GOOGLE_ORGANIC!,
    },
    prices: {
        gmbmaxMonthly: process.env.STRIPE_PRICE_GMB_MAX_MONTHLY!,
        googleorganicMonthly: process.env.STRIPE_PRICE_GOOGLE_ORGANIC_MONTHLY!,
    },
    coupons: {
        SEO70: process.env.STRIPE_COUPON_SEO70!,
        SEO99: 'SEO99',
    },
} as const;



// Helper function to get price ID by service ID
export function getPriceIdByServiceId(serviceId: number): string | null {
    switch (serviceId) {
        case 1:
            return stripeIds.prices.gmbmaxMonthly;
        case 2:
            return stripeIds.prices.googleorganicMonthly;
        default:
            return null;
    }
}

// Helper function to get product ID by service ID
export function getProductIdByServiceId(serviceId: number): string | null {
    switch (serviceId) {
        case 1:
            return stripeIds.products.gmbmax;
        case 2:
            return stripeIds.products.googleorganic;
        default:
            return null;
    }
}
